#version: "2.1"
services:
  server:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - "8112:8111"
    volumes:
      - /mnt/c/users/kristianlund/teamcity-docker-samples/compose-windows/teamcity-server/data:/mnt/c/ProgramData/JetBrains/TeamCity
      - /mnt/c/users/kristianlund/teamcity-docker-samples/compose-windows/teamcity-server/logs:/mnt/c/TeamCity/logs
    mem_limit: 2g
  agent:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}
    environment:
      - SERVER_URL=http://server:8112
      - TEAMCITY_SERVER_MEM_OPTS=-Xmx2g -XX:ReservedCodeCacheSize=350m
#
#volumes:
#  teamcity-server-data:
#    driver: local
#    driver_opts:
#      device: /mnt/c/users/kristianlund/teamcity-docker-samples/compose-windows/teamcity-server/data
#      o: bind
#  teamcity-server-logs:
#    driver: local
#    driver_opts:
#      type: none
#      device: /mnt/c/users/kristianlund/teamcity-docker-samples/compose-windows/teamcity-server/logs
#      o: bind

#C:/Users/KristianLund/teamcity-docker-samples/compose-windows/teamcity-server/data
#C:/Users/KristianLund/teamcity-docker-samples/compose-windows/teamcity-server/logs